version: "3"
services:
  database:
    image: "mongo"
    container_name: "emania-api"
    environment:
      - MONGO_INITDB_DATABASE='emaniaapidatabase'
    volumes:
      - /data/db
    ports:
      - "27017-27019:27017-27019"
